### Get publication summary by ID
GET http://localhost:8081/Projeto_DAE/api/publications/1/summary
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTEwMDcwMiwiZXhwIjoxNzY5MTA0MzAyfQ.opqVeGlv5vTw4bOWLBsc1Cl9iJrvfbITTVUT2sLQNtbSy66tBfrgIFPlqEeQZBov

### Create a publication (With File)
POST http://localhost:8081/Projeto_DAE/api/publications
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTEwMDcwMiwiZXhwIjoxNzY5MTA0MzAyfQ.opqVeGlv5vTw4bOWLBsc1Cl9iJrvfbITTVUT2sLQNtbSy66tBfrgIFPlqEeQZBov

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.pdf"
Content-Type: application/pdf

< ./example.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="publication"
Content-Type: application/json

{
  "title": "Teste",
  "description": "Descrição teste",
  "area": "AI",
  "authors": ["johndoe"],
  "tags": ["AI"]
}
------WebKitFormBoundary7MA4YWxkTrZu0gW--