### Get publication summary by ID
GET http://localhost:8081/Projeto_DAE/api/publications/1/summary
Content-Type: application/json

### Create a publication (With File)
POST http://localhost:8081/Projeto_DAE/api/publications
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.pdf"
Content-Type: application/pdf

< ./example.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="publication"

{
  "title": "My Test Publication",
  "author": "John B. Doe",
  "category": "Science",
  "tags": ["AI"],
  "description": "This is a test publication, hello, hello hello"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW--