### Upload publication
POST http://localhost:8081/Projeto_DAE/api/publications HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTEyOTAxMiwiZXhwIjoxNzY5MTMyNjEyfQ.sqXLFNfeS9IdNhrx7hz6zt5YzvNwD3NMVMcY2pcSWChNSZ3_oxPEMVxVyvuA3RH_
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="file1.txt"
Content-Type: text/plain

contents of the file
--boundary
Content-Disposition: form-data; name="publication"
Content-Type: application/json

{
  "title": "Teste",
  "description": "Descrição teste",
  "area": "AI",
  "authors": ["admin"],
  "tags": ["AI"]
}


### Get all publications
GET http://localhost:8081/Projeto_DAE/api/publications
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTEyOTAxMiwiZXhwIjoxNzY5MTMyNjEyfQ.sqXLFNfeS9IdNhrx7hz6zt5YzvNwD3NMVMcY2pcSWChNSZ3_oxPEMVxVyvuA3RH_

### Get publication by id
GET http://localhost:8081/Projeto_DAE/api/publications/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTEwODExNCwiZXhwIjoxNzY5MTExNzE0fQ.OvTG5q1GrZv_5kUrYC9IMLOEgjk7n2IbT7pVBzzygjwrccfLM4WlK5jxDWtm5Wtr

### Get publication summary by ID
GET http://localhost:8081/Projeto_DAE/api/publications/1/summary
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTEwODExNCwiZXhwIjoxNzY5MTExNzE0fQ.OvTG5q1GrZv_5kUrYC9IMLOEgjk7n2IbT7pVBzzygjwrccfLM4WlK5jxDWtm5Wtr


