### Upload publication
POST http://localhost:8081/Projeto_DAE/api/publications HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTExMzc3NSwiZXhwIjoxNzY5MTE3Mzc1fQ.um8p84hmA5WTstAJRUtXbaXxJRUdfkFoeyUWxAXrJzsiQPsSZqZTTt3yKCHtDkan
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="file1.txt"
Content-Type: text/plain

contents of the file
--boundary
Content-Disposition: form-data; name="publication"
Content-Type: application/json

{
  "title": "Teste",
  "description": "Descrição teste",
  "area": "AI",
  "authors": ["johndoe123"],
  "tags": ["AI"]
}


### Get all publications
GET http://localhost:8081/Projeto_DAE/api/publications
Accept: application/json

### Get publication by id
GET http://localhost:8081/Projeto_DAE/api/publications/1
Accept: application/json

