### REQUEST JWT TOKEN
POST http://localhost:8081/Projeto_DAE/api/auth/login
Content-Type: application/json

{ "username": "johndoe123", "password": "password123" }


### Create Tag
POST http://localhost:8081/Projeto_DAE/api/tags
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTIwMTU5MiwiZXhwIjoxNzY5MjA1MTkyfQ.1M1Rmu08ufCk0T_mIn9w5RsN1cOXha692bQVLLSGzKAHM-09d3JvsqtFVYAdJ34r

{ "name": "AI" }

### Get All Tags
GET http://localhost:8081/Projeto_DAE/api/tags
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE4NjQ4MiwiZXhwIjoxNzY5MTkwMDgyfQ.7pvZ3eGxQ764pfdg518PzsyZiHu0OCPVnWOOzPJyFQMcPZilZf_MvsFX2VU2DC3e


### Get Specific Tag by Name
GET http://localhost:8081/Projeto_DAE/api/tags/AI
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE4NjQ4MiwiZXhwIjoxNzY5MTkwMDgyfQ.7pvZ3eGxQ764pfdg518PzsyZiHu0OCPVnWOOzPJyFQMcPZilZf_MvsFX2VU2DC3e


###Get Hidden Tags
GET http://localhost:8081/Projeto_DAE/api/tags/hidden
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE4NjQ4MiwiZXhwIjoxNzY5MTkwMDgyfQ.7pvZ3eGxQ764pfdg518PzsyZiHu0OCPVnWOOzPJyFQMcPZilZf_MvsFX2VU2DC3e


### Remove tags
DELETE http://localhost:8081/Projeto_DAE/api/tags/AI
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE4NjQ4MiwiZXhwIjoxNzY5MTkwMDgyfQ.7pvZ3eGxQ764pfdg518PzsyZiHu0OCPVnWOOzPJyFQMcPZilZf_MvsFX2VU2DC3e


### Hidden Tag
PUT http://localhost:8081/Projeto_DAE/api/tags/AI
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE4NjQ4MiwiZXhwIjoxNzY5MTkwMDgyfQ.7pvZ3eGxQ764pfdg518PzsyZiHu0OCPVnWOOzPJyFQMcPZilZf_MvsFX2VU2DC3e

{ "visible": "true" }

### Subscribe to Tag
POST http://localhost:8081/Projeto_DAE/api/tags/Ma/subscribe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE4NjQ4MiwiZXhwIjoxNzY5MTkwMDgyfQ.7pvZ3eGxQ764pfdg518PzsyZiHu0OCPVnWOOzPJyFQMcPZilZf_MvsFX2VU2DC3e

### Unsubscribe from Tag
DELETE http://localhost:8081/Projeto_DAE/api/tags/AI/unsubscribe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE4NjQ4MiwiZXhwIjoxNzY5MTkwMDgyfQ.7pvZ3eGxQ764pfdg518PzsyZiHu0OCPVnWOOzPJyFQMcPZilZf_MvsFX2VU2DC3e



