### REQUEST JWT TOKEN
POST http://localhost:8081/Projeto_DAE/api/auth/login
Content-Type: application/json

{ "username": "johndoe123", "password": "password123" }


### Create Tag
POST http://localhost:8081/Projeto_DAE/api/tags
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJqb2huZG9lMTIzIiwiaWF0IjoxNzY5MTkyNTgyLCJleHAiOjE3NjkxOTYxODJ9.y6F4wFvf1R9EXqMIXq0svm5JGP-VgVcZIj9dXXhGB3F5Q7nHPfZTPNvbaUxOcwIc

{ "name": "AI" }

### Get All Tags
GET http://localhost:8081/Projeto_DAE/api/tags
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE0MjEwOSwiZXhwIjoxNzY5MTQ1NzA5fQ.Fcb2NObTuxmHu4htpYlvFRysh9rAHWPOQEXvy3Azsxiu38QjF2L0Cs-eXi8PUsLA


### Get Specific Tag by Name
GET http://localhost:8081/Projeto_DAE/api/tags/AI
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJqb2huZG9lMTIzIiwiaWF0IjoxNzY5MTE5NzYzLCJleHAiOjE3NjkxMjMzNjN9.wyoo5uHZqfHpG7qOETIYjvGSTB56tkw16beGl8hqtz74KFqnienRFS58aFFbNRu6


###Get Hidden Tags
GET http://localhost:8081/Projeto_DAE/api/tags/hidden
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE4Njg0OSwiZXhwIjoxNzY5MTkwNDQ5fQ.yy9w5gLkDWmvvNGrr7J0SAKwMZxvuGL1s14oYhekqDQrirjLFmD3YxkG1tK9Zvx9


### Remove tags
DELETE http://localhost:8081/Projeto_DAE/api/tags/AI
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE4ODI1NiwiZXhwIjoxNzY5MTkxODU2fQ.qghKFOOrYi_l7ru3TLdHtyt-nBN-m9gp_HqeQ36L8cNelY9HEIV0cd3JVC_7YnFM


### Hidden Tag
PUT http://localhost:8081/Projeto_DAE/api/tags/AI
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE4Njg0OSwiZXhwIjoxNzY5MTkwNDQ5fQ.yy9w5gLkDWmvvNGrr7J0SAKwMZxvuGL1s14oYhekqDQrirjLFmD3YxkG1tK9Zvx9

{ "visible": "true" }

### Subscribe to Tag
POST http://localhost:8081/Projeto_DAE/api/tags/Ma/subscribe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE4Njg0OSwiZXhwIjoxNzY5MTkwNDQ5fQ.yy9w5gLkDWmvvNGrr7J0SAKwMZxvuGL1s14oYhekqDQrirjLFmD3YxkG1tK9Zvx9

### Unsubscribe from Tag
DELETE http://localhost:8081/Projeto_DAE/api/tags/AI/unsubscribe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJqb2huZG9lMTIzIiwiaWF0IjoxNzY5MTE5NzYzLCJleHAiOjE3NjkxMjMzNjN9.wyoo5uHZqfHpG7qOETIYjvGSTB56tkw16beGl8hqtz74KFqnienRFS58aFFbNRu6



