### POST new user
POST http://localhost:8081/Projeto_DAE/api/users
Content-Type: application/json

{ "name": "JohnDoe", "email": "test@mail.pt", "password": "password123", "username": "johndoe123" }
###

### GET all users
GET http://localhost:8081/Projeto_DAE/api/users
Accept: application/json
#Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTAyMzg2MCwiZXhwIjoxNzY5MDI3NDYwfQ.s19p1ZzTyeQZKjHfrVwU1hK1VYzkoxJICqiLmrf9RROFq_JI1_oGSyygSUCj0Ybk

###

### GET specific user by username
GET http://localhost:8081/Projeto_DAE/api/users/johndoe123
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTAyMzg2MCwiZXhwIjoxNzY5MDI3NDYwfQ.s19p1ZzTyeQZKjHfrVwU1hK1VYzkoxJICqiLmrf9RROFq_JI1_oGSyygSUCj0Ybk

###

### DELETE user by username
DELETE http://localhost:8081/Projeto_DAE/api/users/johndoe123
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTA4MDY2MywiZXhwIjoxNzY5MDg0MjYzfQ.me60pVLkZyvQFIpulmWwmO8ZKD6IxT8RdQlKXrB6rAMbFwChRmDwMP6vraIwFYvm

###

### PUT update user by username
PUT http://localhost:8081/Projeto_DAE/api/users/johndoe123
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJqb2huZG9lMTIzIiwiaWF0IjoxNzY5MDQyMDE2LCJleHAiOjE3NjkwNDU2MTZ9.tbMUqmOplbnZ4KGgR-mUqdhmljjph8RhPi3NpIXN1MUdWbF7iPBtpemSiF-RlxLS

{ "name": "JohnDoeUpdated", "email": "test1@mail.pt", "password": "password123", "username": "johndoe123", "isActive": true}
###

### POST login user
POST http://localhost:8081/Projeto_DAE/api/auth/login
Content-Type: application/json

{ "username": "johndoe123", "password": "password123" }
###

### POST change password
PUT http://localhost:8081/Projeto_DAE/api/users/johndoe123/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJqb2huZG9lMTIzIiwiaWF0IjoxNzY5MDgxMjU1LCJleHAiOjE3NjkwODQ4NTV9.Ycml4YcuQTqoD6LrBHltciH4qWFcC6x0IY2MRDopZlJM3rQBP4UxnGV_e46H0o63

{ "oldPassword": "password123", "newPassword": "newpassword123" }
###