### POST new user
POST http://localhost:8081/Projeto_DAE/api/users
Content-Type: application/json

{ "name": "JohnDoe", "email": "test@mail.pt", "password": "password123", "username": "johndoe123" }
###

### GET all users
GET http://localhost:8081/Projeto_DAE/api/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE5MzIxOCwiZXhwIjoxNzY5MTk2ODE4fQ.EotQC-jiZOOKzdL3Yskhn2nKEovhHOXabfEXkMEwru_AApJSXFldK8-IITXQQxmp

###

### GET specific user by username
GET http://localhost:8081/Projeto_DAE/api/users/johndoe
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE5MTIxNiwiZXhwIjoxNzY5MTk0ODE2fQ.yBnAJbhbNzrOr7jQFuhcnSsBYqh9XrkaWnHcctfah9pKzNSuI-ocASQCi2f7-6eo

###

### DELETE user by username
DELETE http://localhost:8081/Projeto_DAE/api/users/johndoe123
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTA4MDY2MywiZXhwIjoxNzY5MDg0MjYzfQ.me60pVLkZyvQFIpulmWwmO8ZKD6IxT8RdQlKXrB6rAMbFwChRmDwMP6vraIwFYvm

###

### PUT update user by username
PUT http://localhost:8081/Projeto_DAE/api/users/johndoe123
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJqb2huZG9lIiwiaWF0IjoxNzY5MTI3OTcwLCJleHAiOjE3NjkxMzE1NzB9.oa1XstYqtgC1brioKcoO9U8rehEbh0KJTOs6S3uY12pwA5UCYcmS7yB22InYjBgV

{ "name": "JohnDoeUpdated", "email": "test1@mail.pt", "username": "johndoe123", "isActive": true}
###

### POST login user
POST http://localhost:8081/Projeto_DAE/api/auth/login
Content-Type: application/json

{ "username": "admin", "password": "admin" }
###

### POST change password
PUT http://localhost:8081/Projeto_DAE/api/users/johndoe123/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJqb2huZG9lMTIzIiwiaWF0IjoxNzY5MDgxMjU1LCJleHAiOjE3NjkwODQ4NTV9.Ycml4YcuQTqoD6LrBHltciH4qWFcC6x0IY2MRDopZlJM3rQBP4UxnGV_e46H0o63

{ "oldPassword": "password123", "newPassword": "newpassword123" }
###

### GET user activity
GET http://localhost:8081/Projeto_DAE/api/users/johndoe/activity
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE5MTIxNiwiZXhwIjoxNzY5MTk0ODE2fQ.yBnAJbhbNzrOr7jQFuhcnSsBYqh9XrkaWnHcctfah9pKzNSuI-ocASQCi2f7-6eo

###

### GET user activity
GET http://localhost:8081/Projeto_DAE/api/users/johndoe/history
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE5MTIxNiwiZXhwIjoxNzY5MTk0ODE2fQ.yBnAJbhbNzrOr7jQFuhcnSsBYqh9XrkaWnHcctfah9pKzNSuI-ocASQCi2f7-6eo

### Change User Role
PUT http://localhost:8081/Projeto_DAE/api/users/johndoe123/role
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2OTE5MTkwMSwiZXhwIjoxNzY5MTk1NTAxfQ.k0F7kOUn8CRjXMjgdQufdTgNVadF_lkmzDl9xtLCmlJ_YDnGPZiB623wqbokDYEh

{ "role": "RESPONSIBLE" }
